package pl.school.directo.common;

public enum ResponseCode {
    SUCCESS_CREATED,
    CONFLICT_ID_EXISTS,
    VALIDATION_ERROR,
    SUCCESS_MODIFIED,
    CONFLICT_ID_EXISTS_MODIFICATION,
    FAILED_MODIFICATION,
    SUCCESS_REMOVED,
    OBJ_NOT_FOUND,
    FAILED_CREATION,
    FAILED_REMOVAL

}
