package pl.school.directo.common.Enums;

public enum ResponseCodeEnums {
    SUCCESS_CREATED,
    CONFLICT_ID_EXISTS,
    VALIDATION_ERROR,
    SUCCESS_MODIFIED,
    CONFLICT_ID_EXISTS_MODIFICATION,
    FAILED_MODIFICATION,
    SUCCESS_REMOVED,
    OBJ_NOT_FOUND,
    FAILED_CREATION,
    FAILED_REMOVAL,
    SUCCESS_LOGIN,
    FAILED_LOGIN,
    METHOD_ERROR,
    BLOCKED

}
